Update ddast.yml

diff --git a/.github/workflows/ddast.yml b/.github/workflows/ddast.yml
--- a/.github/workflows/ddast.yml
+++ b/.github/workflows/ddast.yml
@@ -1,29 +1,25 @@
+---
 name: DAST Scan
-
 on:
   push:
     branches:
       - main
-  pull_request:
-    branches:
-      - main
-
 jobs:
   dast:
-    runs-on: self-hosted  # Используем self-hosted runner
+    runs-on: self-hosted
     container:
-      image: owasp/zap2docker-live  # Используем образ OWASP ZAP
-      options: --user root # Добавлены параметры --user и --network
-
+      image: owasp/zap2docker-live
+      options: --user root --network host
     steps:
+      - name: Check current user
+        run: whoami
       - name: Checkout code
         uses: actions/checkout@v4
-
       - name: Run DAST Scan
-        run: |
+        run: >
           echo "Starting DAST scan..."
-          zap-baseline.py -t http://89.169.164.174:80 -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"
 
+          zap-baseline.py -t http://your-target-url.com -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
