Update ddast.yml

diff --git a/.github/workflows/ddast.yml b/.github/workflows/ddast.yml
--- a/.github/workflows/ddast.yml
+++ b/.github/workflows/ddast.yml
@@ -32,8 +32,8 @@ jobs:
 
       - name: Create reports directory
         run: |
-          sudo mkdir -p /home/actions-runner/_work/park/park/zap-reports
-          sudo chmod 777 /home/actions-runner/_work/park/park/zap-reports
+          mkdir -p /home/actions-runner/_work/park/park/zap-reports
+          chmod 777 /home/actions-runner/_work/park/park/zap-reports
 
           # Проверка, что директория создана
           if [ ! -d "/home/actions-runner/_work/park/park/zap-reports" ]; then
@@ -70,7 +70,9 @@ jobs:
       - name: Run DAST scan
         run: |
           # Запуск ZAP с правильными параметрами
-          ./ZAP_2.16.0/zap.sh -cmd -autorun ./ZAP/zap-script.js -dir /home/actions-runner/_work/park/park/zap-reports || { echo "DAST scan failed"; exit 1; }
+          # Укажите URL вашего проекта
+          PROJECT_URL="http://89.169.164.174/myparking/"
+          ./ZAP_2.16.0/zap.sh -cmd -autorun ./ZAP/zap-script.js -url $PROJECT_URL -dir /home/actions-runner/_work/park/park/zap-reports || { echo "DAST scan failed"; exit 1; }
 
           # Проверка, что отчеты созданы
           if [ ! -f "/home/actions-runner/_work/park/park/zap-reports/zap-report.html" ] || [ ! -f "/home/actions-runner/_work/park/park/zap-reports/zap-report.md" ]; then
