Update ddast.yml

diff --git a/.github/workflows/ddast.yml b/.github/workflows/ddast.yml
--- a/.github/workflows/ddast.yml
+++ b/.github/workflows/ddast.yml
@@ -7,31 +7,37 @@ on:
 
 jobs:
   dast:
-    runs-on: self-hosted
-    container:
-      image: owasp/zap2docker-stable
-      options: --user root --network host
-
+    runs-on: self-hosted  # Используем self-hosted runner
     steps:
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
-
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '11'
+
+      - name: Download OWASP ZAP
+        run: |
+          echo "Downloading OWASP ZAP..."
+          ZAP_VERSION="2.16.0"  # Укажите нужную версию ZAP
+          ZAP_URL="https://github.com/zaproxy/zaproxy/releases/download/v${ZAP_VERSION}/ZAP_${ZAP_VERSION}_Linux.tar.gz"
+          wget -O zap.tar.gz $ZAP_URL
+          tar -xzf zap.tar.gz
+          rm zap.tar.gz
+          echo "OWASP ZAP downloaded and extracted."
 
       - name: Run DAST Scan
         run: |
           echo "Starting DAST scan..."
-          # Запуск DAST сканирования
-          zap-baseline.py -t http://89.169.164.174:80 -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"
+          ./ZAP_2.16.0/zap.sh -cmd -autorun /ZAP/zap-script.js -dir zap-reports -r zap-report.html -w zap-report.md || echo "DAST scan failed"
+          echo "DAST scan completed."
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: zap-reports
           path: |
-            zap-report.html
-            zap-report.md
+            zap-reports/zap-report.html
+            zap-reports/zap-report.md
