Update ddast.yml

diff --git a/.github/workflows/ddast.yml b/.github/workflows/ddast.yml
--- a/.github/workflows/ddast.yml
+++ b/.github/workflows/ddast.yml
@@ -46,6 +46,13 @@ jobs:
           ./ZAP_2.16.0/zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true &
           sleep 10 # Даем ZAP время на запуск
 
+      - name: Check if zap-script.js exists
+        run: |
+          if [ ! -f "./ZAP/zap-script.js" ]; then
+            echo "Error: zap-script.js not found in the ZAP directory."
+            exit 1
+          fi
+
       - name: Run DAST scan
         run: |
           # Запуск ZAP с правильными параметрами
