Update ddast.yml

diff --git a/.github/workflows/ddast.yml b/.github/workflows/ddast.yml
--- a/.github/workflows/ddast.yml
+++ b/.github/workflows/ddast.yml
@@ -25,17 +25,18 @@ jobs:
 
       - name: Create reports directory
         run: |
-          mkdir -p /actions-runner/_work/park/park/zap-reports
-          chmod 777 /actions-runner/_work/park/park/zap-reports
+          mkdir -p /home/runner/work/park/park/zap-reports
+          chmod 777 /home/runner/work/park/park/zap-reports
+
       - name: Run DAST scan
         run: |
-          ./ZAP_2.16.0/zap.sh -cmd -autorun /ZAP/zap-script.js -dir ~/actions-runner/_work/park/park/zap-reports -r zap-report.html -w zap-report.md || echo "DAST scan failed"
+          ./ZAP_2.16.0/zap.sh -cmd -autorun /ZAP/zap-script.js -dir /home/runner/work/park/park/zap-reports -r zap-report.html -w zap-report.md || echo "DAST scan failed"
 
       - name: Upload ZAP reports
         uses: actions/upload-artifact@v4
         with:
           name: zap-reports
-          path: /home/pterrosamoilov/actions-runner/_work/park/park/zap-reports
+          path: /home/runner/work/park/park/zap-reports
 
       - name: Create GitHub Issue with ZAP report links
         env:
