Update ddast.yml

diff --git a/.github/workflows/ddast.yml b/.github/workflows/ddast.yml
--- a/.github/workflows/ddast.yml
+++ b/.github/workflows/ddast.yml
@@ -22,10 +22,10 @@ jobs:
       - name: Run DAST Scan
         run: |
           echo "Starting DAST scan..."
-          zap-baseline.py -t http://your-target-url.com -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"
+          zap-baseline.py -t http://89.169.164.174:80 -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"
 
       - name: Upload Artifacts
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: zap-reports
           path: |
