Update SAST and DAST Scan.yaml

diff --git a/.github/workflows/SAST and DAST Scan.yaml b/.github/workflows/SAST and DAST Scan.yaml
--- a/.github/workflows/SAST and DAST Scan.yaml
+++ b/.github/workflows/SAST and DAST Scan.yaml
@@ -58,29 +58,37 @@ jobs:
       - name: Install jq
         run: sudo apt-get install -y jq  # Устанавливаем jq для работы с JSON
 
-      - name: Clone OWASP ZAP repository
+      - name: Download ZAP
         run: |
-          git clone https://github.com/zaproxy/zaproxy.git
-          cd zaproxy
-          git checkout stable  # Используем стабильную ветку
+          mkdir -p ZAP_2.15.0
+          wget -qO- https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_Linux.tar.gz | tar xz -C ZAP_2.15.0 --strip-components=1
 
-      - name: Build ZAP Docker image
-        run: |
-          cd zaproxy
-          docker build -t zap-local .  # Собираем Docker-образ ZAP
+          # Проверяем, что ZAP скачан
+          if [ ! -f "./ZAP_2.15.0/zap.sh" ]; then
+            echo "Error: ZAP download failed."
+            exit 1
+          fi
 
       - name: Create reports directory
         run: |
           mkdir -p zap-reports  # Создаем директорию для отчетов ZAP
 
-      - name: Run ZAP in Docker
+      - name: Set unique ZAP home directory
         run: |
-          docker run -u zap -p 8080:8080 -v $(pwd)/zap-reports:/zap/reports zap-local zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true
+          # Создаем уникальную домашнюю директорию для ZAP
+          export ZAP_HOME=$(mktemp -d)
+          echo "ZAP_HOME set to: $ZAP_HOME"
+
+      - name: Start ZAP in background
+        run: |
+          # Запускаем ZAP в фоновом режиме с уникальной домашней директорией
+          ./ZAP_2.15.0/zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true -dir "$ZAP_HOME" &
+          sleep 10  # Ждем, пока ZAP запустится
 
       - name: Create ZAP script for DAST
         run: |
           # Создаем файл zap-script.js для DAST сканирования
-          cat << 'EOF' > ./zap-script.js
+          cat << 'EOF' > ./ZAP_2.15.0/zap-script.js
           // Скрипт для ZAP
           var targetUrl = "http://89.169.164.174/myparking/"; // URL вашего приложения
           var scanPolicyName = "Default Policy"; // Используемая политика сканирования
@@ -123,7 +131,7 @@ jobs:
 
       - name: Run ZAP script
         run: |
-          docker run -u zap -v $(pwd)/zap-reports:/zap/reports -v $(pwd)/zap-script.js:/zap/script.js zap-local zap.sh -cmd -script /zap/script.js
+          ./ZAP_2.15.0/zap.sh -cmd -script ./ZAP_2.15.0/zap-script.js -dir "$ZAP_HOME"
 
       - name: Upload DAST report
         uses: actions/upload-artifact@v4
